title: Claire-Marie Besnier
logo: /assets/photoCMB-1.png
description: Ingénieure avec 8 ans d’expérience dans l’énergie et l’aménagement urbain, j’ai ajouté une brique data science à mon profil en 2021. Curieuse, méthodique et organisée, j’aime me confronter à des problématiques métier variées, dans un contexte français ou international.
#show_downloads: true
theme: jekyll-theme-minimal
